# Generated by Django 4.0.4 on 2022-05-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sDogAPIApp/media/')),
                ('owner_name', models.CharField(max_length=100)),
                ('shared_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
