# Generated by Django 3.2.6 on 2022-05-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sDogAPIApp', '0003_alter_dog_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='shared_date',
        ),
    ]
