# Generated by Django 3.2.6 on 2022-05-14 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sDogAPIApp', '0004_remove_dog_shared_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dog',
            name='dog_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
